### ISSUE TITLE
User Story: View Blog Posts

### ISSUE THREAD

**Issue by JulianeGampe** [JulianeGampe/travel-blog#13]
As a **user** I can **see the blog posts** so that **I can read about the travel journey**.

## Tasks
- [ ] Create View Code
- [ ] Create a template to render the view
- [ ] Connect the URL
