### ISSUE TITLE
User Story: Delete comments

### ISSUE THREAD

**Issue by JulianeGampe** [JulianeGampe/travel-blog#19]
As a **user** I can **delete my comment** so that **I am able to remove a comment I don´t want to be visible any longer**.

## Tasks
- [ ] Add a delete button to the template
- [ ] Create the view
- [ ] Connect the URL
