### ISSUE TITLE
User Story: Create/Update/Delete Posts from frontend

### ISSUE THREAD

**Issue by JulianeGampe** [JulianeGampe/travel-blog#23]
As a **site owner** I can **create, update and delete my posts from the frontend** so that **I do not need use the admin tool**.

## Tasks
Create Posts:
- [x] Create the profile template
- [x] Create the profile view
- [x] Connect the URL

Update Posts
- [x] Add update button to posts template
- [x] Create EditPostForm in forms.py 
- [x] Create the view
- [x] Create the edit post template
- [x] Connect the URL
- [x] Add the drafts to the post template, visible to superuser

Delete Posts
- [x] Add delete button to posts template
- [x] Create the view
- [x] Create the post delete template
- [x] Connect the URL
