### ISSUE TITLE
User Story: Approve comments from frontend

### ISSUE THREAD

**Issue by JulianeGampe** [JulianeGampe/travel-blog#24]
As a **site owner** I can **approve comments from the frontend** so that **I don't have to use the admin tool**.

## Tasks
- [x] Display comments on profile page with option to approve or delete
- [x] Create approve template to reconfirm approval
- [x] Create approve view
- [x] Connect URL
