### ISSUE TITLE
User Story: Message after commenting/posting

### ISSUE THREAD

**Issue by JulianeGampe** [JulianeGampe/travel-blog#28]
As a **user/site owner** I can **see a message after I have left a comment/created a post on the frontend** so that **I know that the comment/post was successfully generated**.

## Tasks
- [ ] assign message tags in settings.py
- [ ] add the message display in the template
- [ ] add the message to be displayed to the relevant view
