### ISSUE TITLE
User Story: Contact information

### ISSUE THREAD

**Issue by JulianeGampe** [JulianeGampe/travel-blog#3]
As a **user** I can **see contact information** so that **I can get in touch with the site owner**.

## Tasks
- [x] Create the contact app
- [x] Create the view
- [x] Create the template
- [x] Connect the URL
