### ISSUE TITLE
User Story: Read Comments

### ISSUE THREAD

**Issue by JulianeGampe** [JulianeGampe/travel-blog#5]
As a **user/site owner** I can **see the comments** so that **I can read the conversation**.

## Tasks
- [x] Create the comments model
- [x] Create the template
- [x] Create the view
- [x] Connect the URL
